name: Workflow Dispatch Environment Input Example

on:
  workflow_dispatch:
    environment:
      description: 'Environment to deploy'
      type: environment
      required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.environment }} environment"